version: 2.1

executors:
  ruby23:
    docker:
      - image: ruby:2.3
  ruby24":
    docker:
      - image: ruby:2.4
  ruby25":
    docker:
      - image: ruby:2.5
  ruby26":
    docker:
      - image: ruby:2.6

commands:
  ruby:
    parameters:
      gemfile:
        type: string
        default: Gemfile
      command:
        type: string
        default: bundle exec rake test
    steps:
      - checkout
      - run: gem update bundler
      - run: BUNDLE_GEMFILE=<< parameters.gemfile >> ./bundler_version.sh
      - run: BUNDLE_GEMFILE=<< parameters.gemfile >> bundle install
      - run: BUNDLE_GEMFILE=<< parameters.gemfile >> << parameters.command >>

faraday: &faraday
  steps:
    - ruby:
        gemfile: gemfiles/faraday.gemfile

sequel4: &sequel4
  steps:
    - ruby:
        gemfile: gemfiles/sequel4.gemfile

sequel5: &sequel5
  steps:
    - ruby:
        gemfile: gemfiles/sequel5.gemfile

sinatra: &sinatra
  steps:
    - ruby:
        gemfile: gemfiles/sinatra.gemfile

rails_41: &rails_41
  steps:
    - ruby:
        gemfile: gemfiles/rails_41.gemfile

rails_42: &rails_42
  steps:
    - ruby:
        gemfile: gemfiles/rails_42.gemfile

rails_5: &rails_5
  steps:
    - ruby:
        gemfile: gemfiles/rails_5.gemfile

rails_51: &rails_51
  steps:
    - ruby:
        gemfile: gemfiles/rails_51.gemfile

rails_52: &rails_52
  steps:
    - ruby:
        gemfile: gemfiles/rails_52.gemfile

rails_6: &rails_6
  steps:
    - ruby:
        gemfile: gemfiles/rails_6.gemfile

jobs:
  lint:
    executor: ruby26
    steps:
      - ruby:
          command: bundle exec rake rubocop
  faraday_ruby23:
    <<: *faraday
    executor: ruby23
  faraday_ruby24:
    <<: *faraday
    executor: ruby24
  faraday_ruby25:
    <<: *faraday
    executor: ruby25
  faraday_ruby26:
    <<: *faraday
    executor: ruby26

workflows:
  version: 2
  lint:
    jobs:
      - lint
  test:
    jobs:
      - faraday_ruby23
      - faraday_ruby24
      - faraday_ruby25
      - faraday_ruby26
