version: 2.1

executors:
  ruby-two-three:
    docker:
      - image: ruby:2.3
  ruby-two-four:
    docker:
      - image: ruby:2.4
  ruby-two-five:
    docker:
      - image: ruby:2.5
  ruby-two-six:
    docker:
      - image: ruby:2.6

commands:
  ruby:
    parameters:
      gemfile:
        type: string
        default: Gemfile
      command:
        type: string
        default: bundle exec rake test
    steps:
      - checkout
      - run: gem update bundler
      - run: BUNDLE_GEMFILE=<< parameters.gemfile >> ./bundler_version.sh
      - run: BUNDLE_GEMFILE=<< parameters.gemfile >> bundle install
      - run: BUNDLE_GEMFILE=<< parameters.gemfile >> << parameters.command >>

faraday: &faraday
  steps:
    - ruby:
        gemfile: gemfiles/faraday.gemfile

jobs:
  lint:
    executor: ruby-two-six
    steps:
      - ruby:
          command: bundle exec rake rubocop
  faraday-ruby-two-three:
    <<: *faraday
    executor: ruby-two-three
  faraday-ruby-two-four:
    <<: *faraday
    executor: ruby-two-four
  faraday-ruby-two-five:
    <<: *faraday
    executor: ruby-two-five
  faraday-ruby-two-six:
    <<: *faraday
    executor: ruby-two-six

workflows:
  version: 2
  lint:
    jobs:
      - lint
  test:
    jobs:
      - faraday-ruby-two-three
      - faraday-ruby-two-four
      - faraday-ruby-two-five
      - faraday-ruby-two-six
